// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO1ZlBLDwIE8O6rP9-lGY7FyT1VIMuVOU',
    appId: '1:701254219291:web:4af0d10ed9b7c198deaabe',
    messagingSenderId: '701254219291',
    projectId: 'crudmascrist',
    authDomain: 'crudmascrist.firebaseapp.com',
    storageBucket: 'crudmascrist.firebasestorage.app',
    measurementId: 'G-XCCJ5DS12B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzuC7Y1QTpSPyCzAThEXJEajc5pHwr2Ug',
    appId: '1:701254219291:android:59d1147061d1d4e4deaabe',
    messagingSenderId: '701254219291',
    projectId: 'crudmascrist',
    storageBucket: 'crudmascrist.firebasestorage.app',
  );
}
